### ISSUE TITLE
Grid with two rows spans the entire page

### ISSUE THREAD

**Issue by joneuhauser** [tingerrr/subpar#14]
Consider the following example:

```
#import "@preview/subpar:0.1.1"
#set page(
  numbering: "1 / 1",
)

#subpar.grid(
  figure(image("/andromeda.jpg", width:5cm), caption: [
    An image of the andromeda galaxy.
  ]), <a>,
  figure(image("/andromeda.jpg", width:5cm), caption: [
    A sunset illuminating the sky above a mountain range.
  ]), <b>,
  rows: (1fr, 1fr),
  columns: (1fr),
  caption: [A figure composed of two sub figures with a very long caption. It is so long that it even overlaps the page number.],
  label: <full>,
)

Above in @full, we see a figure which is composed of two other figures, namely @a and @b.


```

This currently results in a grid that spans the entire page, and the caption overlaps the page number.

![grafik](https://github.com/user-attachments/assets/1522c0b0-0dbe-4bec-a031-743dd78452c8)

**Comment by tingerrr** [comment]
I can reproduce this with
```typst
#set page(numbering: "1 / 1")

#figure(
  grid(rows: (1fr, 1fr), columns: (1fr)),
  caption: [
    If this caption is long enough, it will go straight into the page footer, possibly directly over the numbering.
  ],
)
```

That's not a subpar issue, but a Typst issue. You can get around this by wrapping this by adjusting the size of the grid or the figure to be a little less than the full page by wrapping it in a block with a rational or set height. But it depends on the caption height, so you either need to use context to measure the caption and adjust the body accordingly, or manually adjust it. See the upstream issue: [typst#4703](https://github.com/typst/typst/issues/4703).

**Comment by joneuhauser** [comment]
Ah, thanks. For me, it works with `columns: (auto, auto)`. It would be nice to have an example for a grid with multiple rows in the manual.
