### ISSUE TITLE
Overwrite the subpar.grid variables?

### ISSUE THREAD

**Issue by Waldehyd** [tingerrr/subpar#20]
Is there a way to overwrite the subpar.grid defaults globally in a template.typ file?

My attempts end up getting "only element functions can be used in set rules" or "cannot access fields on user-defined functions"

**Comment by tingerrr** [comment]
You can define an alias using `.with`:
```typ
#let sgrid = subpar.grid.with(...) // passing defaults similar to set here

#sgrid(...) // using the args set above here
```
