### ISSUE TITLE
text lang keyword not propagating into figure

### ISSUE THREAD

**Issue by AwesomeQuest** [tingerrr/subpar#21]
When using for instance `#set text(lang:"is")` the figure caption does not inherit the figure formatting of the document, meaning it displays "figure N:" and not "Mynd N:" as it should.

**Comment by tingerrr** [comment]
When I wrote the feature to propagate supplements, I had to essentially copy the built-in supplement behavior, and it seems the supplements of `is` might have been added after this feature was initially added. I'll update the list of supplements, but for now you have two ways to get around this:
- set the supplement yourself on the figure using `supplement: [Mynd]`
- turn off propagation by passing `propagate-supplement: false` and it'll make use of the built-in supplement mechanism

The latter will mean that if you mix figure kinds (an image figure containing listings, for example), you may get unexpected results. If you don't do this, turning off propagation should have no downsides.

**Comment by tingerrr** [comment]
Fixed in #22.
